#!/usr/bin/env node
/**
 * Tallinn Tastebuds — the lean copies.
 *
 * The two files every visit to the map downloads, assets/app.js and
 * assets/styles.css, are three fifths prose. That is on purpose: the comments
 * are where the reasoning lives, and CLAUDE.md says not to shorten them. But
 * a phone opening the site for the first time was downloading all of it —
 * 145 KB of app.js over the wire with brotli, 44 of them code; 52 KB of
 * styles.css, 13 of them rules — and no browser reads a comment.
 *
 * So the pages do not load those two files. They load assets/app.lean.js and
 * assets/styles.lean.css, which this tool writes from them: the same code,
 * line for line, with the comments taken out. Nothing is minified, nothing
 * is renamed and the indentation stays, so what devtools shows on the live
 * site is still the readable file — one that reads as the source with the
 * prose removed. The sources stay exactly what they were and are still the
 * only files anybody edits; the lean copies are generated and committed, the
 * way data/places.json and the stamps are, and tools/validate.mjs fails the
 * build when one is not what this tool would write, or when a page still
 * loads a source that has a lean copy.
 *
 * WHAT IS TAKEN OUT, AND WHAT IS NOT
 *
 * In the script, only a comment that opens at the start of a line — after
 * nothing but indentation — is removed, through to its close, however many
 * lines later. A comment on the end of a line of code stays. That is the
 * whole of the rule, and it is that narrow so that it can be trusted without
 * a parser: a block comment cannot open at the start of a line from inside a
 * string, because an ES5 string cannot span lines, nor from inside a regular
 * expression, because `/*` is not one. Everything the rule leaves behind
 * costs a few hundred bytes and buys the certainty that the code the browser
 * runs is the code that was read.
 *
 * In the stylesheet every comment goes, wherever it is, with the quotes
 * tracked so that a `content: "/*"` would survive — there is none today, and
 * the tracking is cheaper than finding out. CSS has no other construct a
 * `/*` can hide in.
 *
 * Runs of blank lines left behind collapse to one, so a stripped paragraph
 * does not leave a page of air. Two lines at the top say where the file came
 * from, so that nobody edits the copy and watches the change vanish on the
 * next run.
 *
 * Usage, after editing either source:
 *
 *     node tools/lean.mjs          write the lean copies
 *     node tools/lean.mjs --check  report a stale one and exit 1
 *
 * Zero dependencies, like every tool here: this still has to run in five
 * years with no `npm install`.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/* Source → copy. A page references the copy; the stamper hashes whichever it
   is told. Adding a file here is one line, and is worth it for a file a
   visitor downloads whose prose outweighs its code — the lists page's two
   would be the next, if they ever are. */
export const LEAN = {
  'assets/app.js': 'assets/app.lean.js',
  'assets/styles.css': 'assets/styles.lean.css'
};

/* The two lines at the top of a copy. */
function banner(src) {
  return `/* Generated by tools/lean.mjs from ${src} — the same code with the comments\n   taken out. Edit that file, not this one, and run the tool. */\n`;
}

/* The script: comments that open at the start of a line, through to their
   close. Walks the text once, line by line, carrying the "inside a comment"
   state across lines. */
export function leanScript(text) {
  const out = [];
  const lines = text.split('\n');
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const lead = line.match(/^\s*/)[0];
    const rest = line.slice(lead.length);
    if (rest.startsWith('//')) { i += 1; continue; }
    if (!rest.startsWith('/*')) { out.push(line); i += 1; continue; }
    /* Opened at the start of this line: find the close, on this line or a
       later one, and keep whatever follows it on the line it closes on. */
    let j = i;
    let from = lead.length + 2;
    let at = lines[j].indexOf('*/', from);
    while (at === -1 && j + 1 < lines.length) {
      j += 1;
      from = 0;
      at = lines[j].indexOf('*/', from);
    }
    if (at === -1) {
      /* Unterminated — not something a file that runs can contain, so keep
         everything from here rather than guess. */
      out.push(...lines.slice(i));
      break;
    }
    const tail = lines[j].slice(at + 2);
    if (tail.trim() !== '') out.push(lead + tail.replace(/^\s+/, ''));
    i = j + 1;
  }
  return collapse(out.join('\n'));
}

/* The stylesheet: every comment, with quotes tracked. */
export function leanStyles(text) {
  let out = '';
  let i = 0;
  let quote = null;
  while (i < text.length) {
    const ch = text[i];
    if (quote) {
      out += ch;
      if (ch === '\\' && i + 1 < text.length) { out += text[i + 1]; i += 2; continue; }
      if (ch === quote) quote = null;
      i += 1;
      continue;
    }
    if (ch === '"' || ch === "'") { quote = ch; out += ch; i += 1; continue; }
    if (ch === '/' && text[i + 1] === '*') {
      const end = text.indexOf('*/', i + 2);
      if (end === -1) { out += text.slice(i); break; }
      i = end + 2;
      continue;
    }
    out += ch;
    i += 1;
  }
  /* A comment that stood on a line of its own leaves the indentation behind;
     take the lines that are now only whitespace, then the runs of blanks. */
  return collapse(out.split('\n').filter((l) => l.trim() !== '' || l === '').join('\n'));
}

/* At most one blank line in a row, no trailing run, and a newline at the end
   like the sources have. */
function collapse(text) {
  return text
    .split('\n')
    .map((l) => (l.trim() === '' ? '' : l))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\n+$/, '') + '\n';
}

/* What the copy of one source should be, now. */
export function render(src) {
  const text = readFileSync(join(ROOT, src), 'utf8');
  const body = src.endsWith('.css') ? leanStyles(text) : leanScript(text);
  return banner(src) + body;
}

/* The copies that are not what this tool would write, for the validator. */
export function stale() {
  const out = [];
  for (const [src, copy] of Object.entries(LEAN)) {
    try {
      const want = render(src);
      const got = existsSync(join(ROOT, copy)) ? readFileSync(join(ROOT, copy), 'utf8') : '';
      if (want !== got) out.push({ src, copy });
    } catch (e) {
      out.push({ src, copy });
    }
  }
  return out;
}

function main() {
  const check = process.argv.includes('--check');
  let bad = 0;
  for (const [src, copy] of Object.entries(LEAN)) {
    if (!existsSync(join(ROOT, src))) {
      console.error(`${src} is missing — nothing to write ${copy} from.`);
      process.exit(1);
    }
    const next = render(src);
    const now = existsSync(join(ROOT, copy)) ? readFileSync(join(ROOT, copy), 'utf8') : '';
    const saved = Math.round((1 - next.length / readFileSync(join(ROOT, src), 'utf8').length) * 100);
    if (now === next) {
      console.log(`${copy} is up to date — ${Math.round(next.length / 1024)} KB, ${saved}% lighter than ${src}.`);
      continue;
    }
    if (check) {
      console.error(`${copy} is stale — run \`node tools/lean.mjs\` and commit the result.`);
      bad += 1;
      continue;
    }
    writeFileSync(join(ROOT, copy), next);
    console.log(`Wrote ${copy} — ${Math.round(next.length / 1024)} KB, ${saved}% lighter than ${src}.`);
  }
  if (bad) process.exit(1);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
